on:
  push:
    branches:
      - main
jobs:
  Check-out-the-code:
    runs-on: self-hosted
    steps:
      - name: actions/checkout@v4.1.2
        run: echo "Checkout finished :)"
      - name: Deploy the code
        run: |
          cd /home/bashkim/
          rm -rf docker_ci_cd
          git clone -b main --single-branch https://${{ secrets.my_token }}@github.com/bashk/docker_ci_cd.git
  Deploy-the-code:
    needs: Check-out-the-code
    runs-on: self-hosted
    steps:
      - name: Stop all and remove all containers if any
        run: |
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker rm $(sudo docker ps -a -q)
      - name: Build the docker
        if: always()
        run: |
          cd /home/bashkim/
          sudo sh ./deploy.sh
